### ISSUE TITLE
Speed Up

### ISSUE THREAD

**Issue by chuxiaoselena** [zyang-ur/onestage_grounding#1]
Great work!

I has been working on to reproduce the results. I find the speed up with multiple gpus does not work really well. Changing from 1 gpu to 8 gpus only give me a 2x speed. What I can do to improve that?

**Comment by zyang-ur** [comment]
Thank you :)

Haven't verified yet, but for me, possible things to try could be:
1. adjust the number of workers, for the possible bottleneck in data loader.
2. pack the images in advance, for the possible bottelneck in I/O. E.g. as a HDF5 file.
3. increasing the batch size should also lead to faster speed.
