### ISSUE TITLE
HELP. Stuck in the second step

### ISSUE THREAD

**Issue by SharonCytheria** [zyang-ur/onestage_grounding#10]
Sorry to interrupt, but I was kind of wondering how can I actually download the ReferItGame datasets. I tried and was failed to use the "download_dataset.sh" to get the datasets, since the resources had been deleted(I suppose) from the Berkeley EECS net. 
I will highly appreciate it if someone can send me the "Referitdata.tar and ReferIt_splits.tar".
My email is sherlock_sss@163.com
Many thanks :)

**Comment by frankfufuu** [comment]
@SharonCytheria hi I have same problem. Did you get the ReferItGame datasets? If you got it, could you send it to my email, thanks :D
My email is 1061189239@qq.com
