### ISSUE TITLE
How to get the referit_train and corpus.pth in data/referit folder

### ISSUE THREAD

**Issue by frankfufuu** [zyang-ur/onestage_grounding#11]
Hi 
I am trying to construct my own dataset and wonder how to build my own data.pth and corpus.pth as the files downloaded in ./data file?

**Comment by zyang-ur** [comment]
Hi @frankfufuu,

The corpus is inherited from the DMS repo: https://github.com/BCV-Uniandes/DMS/blob/master/dmn_pytorch/referit_loader.py

You could check the dataload and related utils functions to generate the corpus file.
