### ISSUE TITLE
URL in download_data.sh invalidate

### ISSUE THREAD

**Issue by VinAjuu** [zyang-ur/onestage_grounding#12]
The download URL of  Referit and Referit Split is invalid, I can't find the correct resources on the internet. Could you please tell me how to download the two datasets if you still have some ideas about them?

**Comment by zyang-ur** [comment]
Hi @VinAjuu ,

Please kindly send me an email, I'm happy to share my copy privately. Thank you.

Best,
Zhengyuan

**Comment by Rose-bud** [comment]
> I had the same problem, would you please send me a copy of the Referit dataset? Thank you very much indeed. Here is my email： 3026960386@qq.com, Thanks!!!

**Comment by bobo123yhb** [comment]
I had the same problem, would you please send me a copy of the Referit dataset? Thank you very much indeed. Here is my email： [3026960386@qq.com](mailto:1667662807@qq.com), Thanks!!!

**Comment by bobo123yhb** [comment]
I had the same problem, would you please send me a copy of the Referit dataset? Thank you very much indeed. Here is my email： [1667662807@qq.com](mailto:1667662807@qq.com), Thanks!!!
