### ISSUE TITLE
Generate index cache

### ISSUE THREAD

**Issue by leotam** [zyang-ur/onestage_grounding#3]
How would you go about generating the index cache files for a new dataset?  

In ln. 204 of the ReferDataset class there's this commented line:

            # self.process_dataset()

**Comment by zyang-ur** [comment]
Please kindly refer to this repo for generating the cache files:
https://github.com/BCV-Uniandes/DMS/blob/9fa3a3a2ef5980dd17e21b73234a4cd0b3d00e16/dmn_pytorch/referit_loader.py#L102
