### ISSUE TITLE
pretrained models are not available

### ISSUE THREAD

**Issue by TransformersWsz** [zyang-ur/onestage_grounding#4]
- When decompressing `bert_flickr_model.pth.tar` downloaded from [Gdrive](https://drive.google.com/drive/folders/1-DXvhEbWQtVWAUT_-G19zlz-0Ekcj5d7), it reports error `tar: Error opening archive: Unrecognized archive format`.
- [One Drive](https://uofr-my.sharepoint.com/:f:/g/personal/zyang39_ur_rochester_edu/ErrXDnw1igFGghwbH5daoKwBX4vtE_erXbOo1JGnraCE4Q?e=tQUCk7) link has expired.

**Comment by zyang-ur** [comment]
Hi, 

The downloaded model can be directly loaded by "--resume bert_flickr_model.pth.tar," no need to untar.

Thank you for the reminder. The files in One Drive are identical to the ones Gdrive, I'll update the links.
