### ISSUE TITLE
Training on refcoco+ dataset

### ISSUE THREAD

**Issue by zhaipeichen** [zyang-ur/onestage_grounding#6]
Hi,

Thank you for the great work!

I want to use the project,it can help me a lot for my lessons. Then I want to know:

 How can I train refcoco+ dataset? Where I should modify the code? 

Thank you very much for your advance.

**Comment by zyang-ur** [comment]
Hi,

Thank you for your interest.

Simply changing the dataset argument from "unc" to "unc+" should make it work. You could also reference our related work (https://github.com/zyang-ur/ReSC) that experiments on refcoco+, in case you wish to have a pre-trained model. Thanks.
