### ISSUE TITLE
Appendix B. Cross-Sample Relationships

### ISSUE THREAD

**Issue by OliverHuang1220** [zyang-ur/onestage_grounding#9]
Hi@zyang-ur,i am reading you FAOA paper.Is there any code for  cross-sample methods？

**Comment by zyang-ur** [comment]
Hi @OliverHuang1220 

You could reference the following repo on the contrastive loss implementation. https://github.com/KunpengLi1994/VSRN/blob/777ae74326fdb6abe69dbd3911d0e545322520d1/model.py#L356

Besides, here is a related work focusing on the cross-sample method. https://arxiv.org/abs/2104.10156

**Comment by OliverHuang1220** [comment]
Wow,Your reply is very useful to me,I'll study it carefully，Thanks！:)
